### ISSUE TITLE
does have script php server?

### ISSUE THREAD

**Issue by mahdi00021** [RobertNorthard/distributed-taxi-booking-system-android-client#4]
does have script php server?

**Comment by RobertNorthard** [comment]
Nope, the service side component (https://github.com/RobertNorthard/distributed-taxi-booking-system-server) is also written in Java. However, the applications protocols used in the application (HTTP, WSS) have great interoperability. You can find an example web app here (https://github.com/RobertNorthard/distributed-taxi-booking-system-server/tree/master/src/main/webapp).
